TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID"
PRICE_POLL_INTERVAL_SECONDS = 10
BINANCE_API_KEY = ""
BINANCE_API_SECRET = ""
SQL_SERVER = "localhost"          
SQL_DATABASE = "PortfolioDB"
SQL_TRUSTED_CONNECTION = True      
